### ISSUE TITLE
Should use `font-awesome` instead of `fa` for the Font Awesome id/name

### ISSUE THREAD

**Issue by KZeni** [kucrut/wp-icon-picker#27]
Using something just called `fa` doesn't give other plugins, themes, etc. the needed confidence to dequeue the included Font Awesome when they need to since there's plenty of stuff which might happen to be named `fa`. Meanwhile, calling it `font-awesome` leaves no wiggle room & would be recommended.

Also, this is a more standardized name which greatly reduces the change that Font Awesome's called more than once on a given site (ex. one plugin uses the more standard `font-awesome` name while this one uses `fa` so the site sees them as separate items which are then called when only one is actually needed.)

I don't see any downside to making this id more descriptive / standardized.

I have also posted about this on the WordPress.org support forum here: https://wordpress.org/support/topic/fontawesome-4-7-0/#post-9216454

**Comment by kucrut** [comment]
Thank you for the report @KZeni! I'm currently updating Font Awesome to the latest version and I'll see what I can do about this while keeping backwards-compatibility.

**Comment by kucrut** [comment]
Actually, the stylesheet is registered as `font-awesome`. The ID itself is only used by Icon Picker internally.

I'm closing this issue. Feel free to re-open it if you're still having issue.
