### ISSUE TITLE
WP 4.4 Compatilbility Issues

### ISSUE THREAD

**Issue by jmotes** [kucrut/wp-icon-picker#3]
My Font Awesome icons settings got erased from menus during the last update. Also, after upgrading to WP 4.4 the icon "families" sidebar is gone and I can no longer select a icon set - the only ones available for selection are Dashicons, so I can't reapply the missing icons in my menus.

**Comment by kucrut** [comment]
@jmotes Please take a look at this support thread: https://wordpress.org/support/topic/icons-functionality-removed-in-latest-update?replies=21
