### ISSUE TITLE
Add custom icon sets

### ISSUE THREAD

**Issue by tareiking** [kucrut/wp-icon-picker#7]
Hi @kucrut - It would be great to allow developers to add their own icon sets via filters, similar registration process to adding [custom meta box fields](https://github.com/humanmade/Custom-Meta-Boxes/wiki/Adding-your-own-field-types) would be ideal.

It appears that the current method of adding custom is to add your custom icon picker types into the plugin as the assets and classes are enqueued based on [this line](https://github.com/kucrut/wp-icon-picker/blob/master/icon-picker.php#L265)?

**Comment by kucrut** [comment]
@tareiking To add a custom type, you can use the `icon_picker_types_registry_init` action hook. See complete example in the [IcoMoon extension](https://github.com/kucrut/wp-menu-icons-icomoon/), particulary [this line](https://github.com/kucrut/wp-menu-icons-icomoon/blob/master/menu-icons-icomoon.php#L44).

**Comment by tareiking** [comment]
Thanks for the IcoMoon extension link @kucrut! I took a slightly different route with `icon_picker_types_registry_ready` filter, but the IcoMoon example is perfect!

Closing issue!
